name: Daily Commit Report

on:
  schedule:
    # Runs daily at 09:00 IST (03:30 UTC)
    - cron: "30 3 * * *"
  # You can also run it manually and choose a branch/time window
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to scan (leave empty to use default branch)"
        required: false
        default: ""
      hours:
        description: "How many past hours to check"
        required: false
        default: "24"

jobs:
  report:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
      - name: Generate commit report
        uses: actions/github-script@v7
        with:
          script: |
            const owner = context.repo.owner;
            const repo  = context.repo.repo;

            // 1) figure out branch
            const { data: repoData } = await github.rest.repos.get({ owner, repo });
            const defaultBranch = repoData.default_branch;
            const inputBranch = core.getInput('branch')?.trim();
            const branch = inputBranch || defaultBranch;

            // 2) time window (default 24h)
            const hours = Number(core.getInput('hours') || '24');
            const since = new Date(Date.now() - hours*60*60*1000).toISO*
